{{- $dot := . -}}

{{- range .Values.backupJobs }}
{{- if $.Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "db-archive.fullname" $dot }}-{{ .name }}
  labels:
    {{- include "db-archive.labels" $dot | nindent 4 }}
    job.{{ $.Chart.Name }}/dbType: {{ .dbType | quote }}
  {{- with $.Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "db-archive.serviceAccountName" $dot }}
          containers:
          - name:  {{ .name }}-backup
            image: {{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            securityContext:
              {{- toYaml $.Values.podSecurityContext | nindent 14 }}
            env:
              - name: "DA_DB_TYPE"
                value: {{ .dbType | quote }}
              - name: "DA_SOURCE_HOST"
                value: {{ .sourceHost | quote }}
              - name: "DA_SOURCE_USERNAME"
                value: {{ .sourceUser | quote }}
              - name: "DA_SOURCE_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: {{ .sourcePasswordSecretName }}
                    key: password
              - name: "DA_DESTINATION_BUCKET"
                value: {{ .bucketName | quote }}
              {{- toYaml .additionalEnvs | nindent 14}}
            args:
              {{- with .additionalArgs -}}
              {{- toYaml . | nindent 16}}
              {{- end -}}
              {{- with .dbToBackup }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
            resources:
              {{- toYaml $.Values.resources | nindent 14 }}
            {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
{{- end }}
